### ISSUE TITLE
hal-deploy-apply job failure

### ISSUE THREAD

**Issue by jumpydiaz** [GoogleCloudPlatform/spinnaker-for-gcp#110]
Hello, 
I am following the guide for installation on GCP and I keep encountering the same issue, the installation hangs when it gets to the hal-deploy-apply stage. I am not making any changes to the properties file. Here is the terminal output showing the error I get, followed by the endless series of dots (email address has been changed for privacy). I'm sure it's something obvious that I'm missing, but I can't pin down a succinct answer online regarding the error message. I'd appreciate any help you can give. 

.  Provisioning Spinnaker resources... 
namespace/halyard created
namespace/spinnaker created
persistentvolumeclaim/halyard-pv-claim created
statefulset.apps/spin-halyard created
service/spin-halyard created
configmap/halconfig created
job.batch/hal-deploy-apply created
Error from server (Forbidden): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "email@address.com" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
Waiting on job hal-deploy-apply to complete...............................................................................................................................................................................................................

**Comment by alfredtommy** [comment]
@jumpydiaz 
How did you finally resolve the issue?

I am going through the exact same issue, except I'm trying to deploy to an existing cluster. The service account I am using has the right permissions and all the steps are successful until it reaches the stage where the hal job has to be created. 

For me it gets stuck on the same line (note: this is after re-running the script):

.  Using existing pubsub topic projects/searce-sandbox/topics/spinnaker-1-notifications-topic for notifications... 
Deleting earlier job hal-deploy-apply... 
job.batch "hal-deploy-apply" deleted
Provisioning Spinnaker resources... 
namespace/halyard unchanged
namespace/spinnaker unchanged
clusterrolebinding.rbac.authorization.k8s.io/spinnaker-admin unchanged
persistentvolumeclaim/halyard-pv-claim unchanged
statefulset.apps/spin-halyard unchanged
service/spin-halyard unchanged
configmap/halconfig unchanged
job.batch/hal-deploy-apply created
Waiting on job hal-deploy-apply to complete....................................................................................................................................
.............................................

The logs show CrashLoopBackoff, and then eventually -> BackoffLimitExceeded.
I don't understand why it is unable to successfully deploy the job, when all the previous commands in the setup script are executing properly.

P.S: I don't get any errors when I create new cluster with default settings, but I'm trying to deploy to an existing cluster. I'm attaching the logs here. **Note that the service account I am using has editor permissions and project IAM admin permission.**

![image](https://user-images.githubusercontent.com/20069889/77912050-81c16580-72af-11ea-8027-626094907b41.png)
![image](https://user-images.githubusercontent.com/20069889/77912087-8dad2780-72af-11ea-84a3-95fe0ad3d8c2.png)
