### ISSUE TITLE
Workload identity not working with spinnaker

### ISSUE THREAD

**Issue by adamdavis40208** [GoogleCloudPlatform/spinnaker-for-gcp#112]
https://github.com/spinnaker/spinnaker/issues/4838

Just an FYI -- we were interested in the cleaner management of service accounts using workload identity, but spinnaker (installed via spinnaker-for-gcp) has a couple of components that don't seem to enjoy working along with it.

It might be me doing something silly, but it's working with non-spinnaker pods.

**Comment by demobox** [comment]
Thanks for raising this, Adam!

A quick question to clarify: are we talking about using the identity attached to the clouddriver pod (via Workload Identity) as the credential that is used to deploy to other clusters? Or do you have something different in mind here?

**Comment by adamdavis40208** [comment]
Yeah, that exactly. It's much more secure than storing a secret, but I also understand that it's very gke specific. Not sure if spinnaker wants to go down the route of supporting gke only kubernetes features

**Comment by demobox** [comment]
@duftler FYI ^^

**Comment by duftler** [comment]
These are the rough steps that will be required to make Spinnaker for GCP work with Workload Identity:

- [ ] Add newer google auth library to kork: https://github.com/spinnaker/kork/pull/390
- [ ] Update each service to match the changes that were made to front50 here (thanks for doing all the digging on this, @adamdavis40208 ): https://github.com/spinnaker/front50/pull/605
- [ ] Add logic to Spinnaker for GCP to:
  - [ ] Enable workload identity on the cluster
  - [ ] Create "Spinnaker service"-specific Kubernetes service accounts
  - [ ] Create "Spinnaker service"-specific Google service accounts
  - [ ] Create GCP IAM bindings between the pairs of service accounts
  - [ ] Modify each service's pod spec to specify the appropriate Kubernetes service account (have verified that halyard will allow for the service accounts to be specified via configuration: https://github.com/spinnaker/halyard/pull/1450)
  - [ ] Modify each service's pod spec to specify the annotation telling it which Google service account to use when calling GCP api's

**Comment by demobox** [comment]
Thanks for the investigation, @duftler! It looks like the first two items will require changes to Spinnaker OSS; once that's done, is there a way for users to run through the remaining steps "by hand" to validate this approach before we consider how to automate this?

**Comment by duftler** [comment]
For starters, we can document the steps we've taken to verify it works. If that all goes smoothly, scripting those steps shouldn't be too much additional work.

**Comment by duftler** [comment]
This PR adds an experimental script that will enable workload identity: https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/pull/142
