### ISSUE TITLE
OAuth doesn't work

### ISSUE THREAD

**Issue by mavenraven** [GoogleCloudPlatform/spinnaker-for-gcp#113]
Followed the tutorial, get this at the end:

![Screen Shot 2019-09-08 at 1 34 20 PM](https://user-images.githubusercontent.com/26941/64492027-4bea6000-d23d-11e9-9c84-b4ece68281df.png)

**Comment by duftler** [comment]
Can take a while, maybe 30 minutes or more, for the cert to be registered.

**Comment by mavenraven** [comment]
Yeah it's working now, thanks @duftler
