### ISSUE TITLE
SERVICE_ACCOUNT_NAME -- must match displayName vs member name

### ISSUE THREAD

**Issue by adamdavis40208** [GoogleCloudPlatform/spinnaker-for-gcp#117]
Some background: we are creating the kubernetes cluster, and a few other things (network, service account, etc) via terraform.

Then I'm running the setup scripts from cloud shell.

the setup script gets the iam user via:

```
SA_EMAIL=$(gcloud iam service-accounts --project $PROJECT_ID list \
 --filter="displayName:$SERVICE_ACCOUNT_NAME" \
--format='value(email)')
```

the iap script however:

```
gcloud iam service-accounts keys create ~/.spin/key.json \
--iam-account $SERVICE_ACCOUNT_NAME@$PROJECT_ID.iam.gserviceaccount.com \
```

So unless your service account is created a very specific way, one script is going to bomb out. 

The setup script creates it as:

```
 gcloud iam service-accounts --project $PROJECT_ID create \
    $SERVICE_ACCOUNT_NAME \
    --display-name $SERVICE_ACCOUNT_NAME
```
Which is why the project functions correctly.

**Comment by demobox** [comment]
@adamdavis40208 Just to clarify: what is **not** working is if you "bring your own service account" and edit the `SERVICE_ACCOUNT_NAME` property in the properties file?

So the functionality we're looking for here is "if I set `SERVICE_ACCOUNT_NAME` to my value, things should work"?
