### ISSUE TITLE
Certificate mismatch when accessing spinnaker UI

### ISSUE THREAD

**Issue by JeffCertain** [GoogleCloudPlatform/spinnaker-for-gcp#120]
After following the directions for exposing Spinnaker, I can log into the server using oauth. After some period of time (a few hours), I start getting certificate mismatches, and all logins give me the following error:

> Untrusted SSL Server Certificate (ssl_server_cert_untrusted_issuer)
> --
> Your request contacted a host which presented a certificate signed by an untrusted issuer.
> This is typically caused by a Web Site presenting an incorrect or invalid certificate, but could be because of a configuration error.
> For assistance, contact your network support team.

**Comment by demobox** [comment]
Just to clarify: this actually worked initially, and _then_ started failing? And it's still failing now, or was it a transient issue?

Would it be possible for you to try creating another Spinnaker for GCP instance from the Management Console and securing that too? Just trying to figure out if this is a one-off or potentially related to your account/setup in some way?

**Comment by JeffCertain** [comment]
That's correct. I exposed spinnaker via IAP, waited for a little while, and
connected successfully. After some time, I could no longer connect. There
was a timeout for inactivity in the mix.

I've gone through that tutorial a couple of times now, starting new
projects each time. The behaviour is consistent. However, I'm happy to run
through the creation of a new project today to see if it happens again.

**Comment by demobox** [comment]
> The behaviour is consistent.

Hm, interesting - not something we've seen before, indeed. @duftler thoughts on potential next steps to debug? Any error messages or logs to look out for?

**Comment by duftler** [comment]
I've so far been unable to reproduce this. I've tried creating multiple projects and Spinnaker deployments from scratch, from yesterday through this morning, with both internal and external accounts.

In the hope that we spot some meaningful clue, I've captured screen-grabs of the relevant resources in cloud console. Maybe you see something that looks different/unhealthy in your environment?

![image](https://user-images.githubusercontent.com/8437718/65260119-dea7bc00-dad3-11e9-87d9-9c9c59f25e30.png)
![image](https://user-images.githubusercontent.com/8437718/65260138-e5363380-dad3-11e9-8ba6-9917153532dd.png)
![image](https://user-images.githubusercontent.com/8437718/65260152-ea937e00-dad3-11e9-92fb-b3bc09784f79.png)
![image](https://user-images.githubusercontent.com/8437718/65260169-f0895f00-dad3-11e9-92e3-08d322b742a3.png)
![image](https://user-images.githubusercontent.com/8437718/65260179-f54e1300-dad3-11e9-9e6b-92b3d113be4a.png)
![image](https://user-images.githubusercontent.com/8437718/65260190-fb43f400-dad3-11e9-8414-353952d40f46.png)

**Comment by duftler** [comment]
Could also look for clues by dropping the domain name into any of the public ssl checker sites.

**Comment by JeffCertain** [comment]
This happened again this morning with a new project.

I'm working my way through the automated canary stage via Kayenta (
https://cloud.google.com/solutions/automated-canary-analysis-kubernetes-engine-spinnaker).
Somewhere about the time that I enable Kayenta, I get logged out of my
spinnaker instance, and I start seeing the SSL certificate mismatch.

What's really weird is that the certificate checks out with sslshopper.com.
(https://spinnaker-1.endpoints.spinnaker-test-253416.cloud.goog)

The problem persists in anonymous mode, and after re-running the IAP script.

Looking at the screenshots, the "Backend Service Details" pretty clearly
show no traffic is making it to the box
[image: Screen Shot 2019-09-19 at 11.35.35 AM.png]

Other than that, everything looks good.

~ Jeff

**Comment by JeffCertain** [comment]
Don't know if this helps, but when I try to hit the same instance after
re-running "connect_unsecured.sh" and using the web preview on 8080, I get "
Error fetching applications. Check that your gate endpoint is accessible.
Further information on troubleshooting this error is available here."

**Comment by JeffCertain** [comment]
I think it's likely that something in the Kayenta demo, around the
"automated canary" steps put spinnaker into a bad state. Starting a new
project from scratch and following the directions in that tutorial ends up
with spinnaker throwing SSL errors even exposed only via port forwarding.

At least, I created a brand new project, and started that tutorial, and ran
into the same problem about that point.
https://cloud.google.com/solutions/automated-canary-analysis-kubernetes-engine-spinnaker

This is now 7 spinnaker tutorials that have ended up in this state, so it's
pretty repeatable. (Previous projects started with the spinnaker tutorial,
then I moved on to the canary tutorial.)

~ Jeff

**Comment by duftler** [comment]
Ah, didn't realize that you were working through the Kayenta solution. I'll try reproducing by running through that as well.

**Comment by JeffCertain** [comment]
This is getting both more frustrating and more bizarre.

I spun up a completely new gmail account, and followed through the Kayenta
tutorial. I had a good five or six hours where Spinnaker was stable. Then I
got the SSL issue. This was end of day Friday.

On a hopeful whim, I restarted cloud shell, did the port-forwarding
dance... and, lo! My spinnaker instance is still there.

~ Jeff

**Comment by bgood** [comment]
Jeff,
I tried reproducing this last night and my Spinnaker with IAP is still working this morning.  To make sure I did the correct scenario I have a couple questions.

Is this only happening with the canary analysis tutorial or does it happen with other tutorials as well?

Does the SSL problem happen when you run the `hal` commands and `push_and_apply.sh` to setup canary analysis, or is more to do with time?

Thanks
Ben

**Comment by JeffCertain** [comment]
Hi Ben,

It seems to be really unpredictable. At first I thought it was just happening early on, and that letting it bake a little longer would help. Then, on Friday, the problem manifested itself after 6 hours or so.

I'm starting to suspect this might actually be the result of some corporate security protocols that sometimes mess with certificates. It has, for the most part, been stable this week.

~ Jeff

**Comment by JeffCertain** [comment]
Looks like it was, in fact, internal security protocols. So frustrating!!

**Comment by demobox** [comment]
> Looks like it was, in fact, internal security protocols. So frustrating!!

Thanks for getting back to confirm that!
