### ISSUE TITLE
Spinnaker setup hangs on existing GKE if api scopes are missing 

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/spinnaker-for-gcp#123]
On an existing GKE cluster spinnaker deployment hangs, in case underlying GKE nodes do not have required api scopes. Screen shot below.

![image](https://user-images.githubusercontent.com/3214330/65622459-8c0a4c00-df7a-11e9-8042-2c916d66d577.png)

**Comment by demobox** [comment]
@shashank-google A cluster with missing prerequisites should cause the setup process to fail now
