### ISSUE TITLE
Support External Account Configuration

### ISSUE THREAD

**Issue by gnarea** [GoogleCloudPlatform/spinnaker-for-gcp#126]
I think this solution doesn't support [External Account Configuration](https://www.spinnaker.io/setup/configuration/), at least not the way is documented on spinnaker.io because spinnaker-for-gcp doesn't seem to support specifying Spring Cloud Config values.

If this is correct, is there any workaround I could use in the meantime?

**Comment by gnarea** [comment]
Hey folks. Any idea whether this is supported or how I can use it?

**Comment by demobox** [comment]
> because spinnaker-for-gcp doesn't seem to support specifying Spring Cloud Config values

Could you provide a bit more detail about what you tried to do? You should have full access to the configuration of the instances Spinnaker for GCP sets up for you, and should also be able to use any Spinnaker OSS version. So it would be helpful to know what you tried and what didn't work, or where it wasn't clear how to do what the docs were asking you to do.

Thanks!

**Comment by gnarea** [comment]
Hey @demobox. Thanks for getting back to me!

I didn't get far at all as I was lost from the very beginning. It all boils down to a very simple question: Where do I set `spring.cloud.config.server.git` when I use Spinnaker for GCP?

The docs say the following early on:

> To enable external configuration via the Config Server, add Spring Cloud Config configuration properties, which are under spring.cloud.config.server, and include settings for the backend you wish to use. If you deploy Spinnaker manually, you might place this configuration in a YAML file called spinnakerconfig.yml, alongside your spinnaker.yml file.

I have no idea what they mean by deploying Spinnaker "manually" (I only know of one way to deploy Spinnaker and that's `hal deploy apply`) or whether Spinnaker for GCP would be classed as "deploying Spinnaker manually"; either way, neither of the two files above exist according to `find $HOME -name spinnakerconfig.yml -or -name spinnaker.yml`.

I tried adding the following to my `.hal/config`:

```
spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/example/spinnaker-config
          refresh-rate: 10
```

But `push_and_apply.sh` failed with the following error:

```
ERROR Could not translate your halconfig: Unrecognized field
  "spring" (class com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig),
  not marked as ignorable (3 known properties: "deploymentConfigurations",
  "halyardVersion", "currentDeployment"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["spring"])
```

**Comment by wilddog64** [comment]
I think the document ask you to push spinnakerconfig.yml and spinnaker.yml side by side in the same directory, not put the content in spinnaker.yml

**Comment by gnarea** [comment]
Hi. But where exactly do I put the file(s)? Note that neither exist as
mentioned above.

**Comment by wilddog64** [comment]
If you read the https://www.spinnaker.io/setup/configuration/, you should
find these two lines

To enable external configuration via the Config Server, add Spring Cloud
Config configuration properties, which are under spring.cloud.config.server,
and include settings for the backend you wish to use.

*If you are deploying Spinnaker using Halyard, you can place this file
under the ~/.hal/$DEPLOYMENT/profiles*

**Comment by gnarea** [comment]
Oh, that was added last week: https://github.com/spinnaker/spinnaker.github.io/commit/b93e33aa5e34a0b59967cee6a401831e8ee6970b#diff-5fd2f4edaf75d04a9eea3d6ef989a46e

So in that case I have the info I need.

Thanks!
