### ISSUE TITLE
setup and manage multiple spinnaker for multiple projects

### ISSUE THREAD

**Issue by wilddog64** [GoogleCloudPlatform/spinnaker-for-gcp#144]
So far spinnaker-for-gcp assumes it is at $HOME/spinnaker-for-gcp directory. This does not make easy for managing multiple projects. Ideally the setup.sh, setup_properties.sh should be able to resolve to script's running directory. This way, users can put this repo in any directory they like rather than $HOME/spinnaker-for-gcp. 

    function getScriptDir() {
    # so this script won't be affect by CDPATH variable
    unset CDPATH
    SOURCE="${BASH_SOURCE[0]}"
    # resolve $SOURCE until the file is no longer a symlink
    while [ -h "$SOURCE" ]; do
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        # if $SOURCE was a relative symlink, we need to resolve it relative to the
        # path where the symlink file was located
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    done
    echo "$( cd -P "$( dirname "$SOURCE" )" && pwd )"

}

SCRIPT_DIR=$(getScriptDir)/..

The above snippet can resolve to running script's directory (it can also follow the link). Maybe consider put that into bash scripts?

**Comment by demobox** [comment]
Do you mean multiple GCP projects or multiple Spinnaker instances? The intended design is that the *same* `spinnaker-for-gcp` repo [can be used to manage _many_ Spinnaker instances](https://cloud.google.com/docs/ci-cd/spinnaker/spinnaker-for-gcp#manage_multiple_spinnaker_installations) - the `pull_config.sh` command will ensure the configuration of the targeted Spinnaker instance is retrieved and used.

**Comment by wilddog64** [comment]
Multiple projects.

**Comment by duftler** [comment]
The scripts should only be run from the `$HOME/spinnaker-for-gcp` directory, as designed.

If the instructions are followed, it can safely be used to manage multiple Spinnaker installations, across multiple GCP projects.

There are some details [here](https://cloud.google.com/docs/ci-cd/spinnaker/spinnaker-for-gcp#manage_multiple_spinnaker_installations) on managing multiple installations. If you follow those steps, all that remains is to refresh the management console via `~/spinnaker-for-gcp/scripts/manage/update_console.sh`.

We still recommend an admin/operator wishing to manage an installation start from the Kubernetes Engine->Applications view in the Cloud Console. The link in the application details view will open Cloud Shell and bring up the management console. Then you need to ensure you are corrected to the correct cluster, pull the config, and refresh the console. These are the exact commands that come up in the console by default when cloning the repo.

The workflow is basically:
- Open Cloud Shell and the management console (that is, the documentation in the right-hand pane)
- Ensure you are corrected to the correct cluster in the correct project
- Pull the config from that Spinnaker installation
- Refresh the management console so the various commands and links properly reflect the installation being managed

**Comment by wilddog64** [comment]
What about multiple projects? I believe scripts can handle multiple
spinnaker instances. But I wonder if it can handle different project.

**Comment by duftler** [comment]
Yes, it works across multiple projects. This is why the first section of the management console guidance requires you to select a project.

**Comment by wilddog64** [comment]
As far as I know spinnaker-for-gcp does not work well with multiple
projects. If you switch to a different project, besides you have to switch
project, you also need to clean up properties file. I think ideally, the
scripts should be able to resolve execution path. This way, I can use a
different directory to manage different project.

**Comment by duftler** [comment]
> If you switch to a different project, besides you have to switch
project, you also need to clean up properties file.

This is incorrect.

The `pull_config.sh` script replaces all of the relevant config files, including the `properties` file (you can see the actual command here: https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/blob/master/scripts/manage/pull_config.sh#L55).

If you are switching projects and your `properties` file is not being updated, please open an issue with exact steps to reproduce.
