### ISSUE TITLE
There was an error saving your pipeline: No message available. [dismiss]

### ISSUE THREAD

**Issue by girisha-g** [GoogleCloudPlatform/spinnaker-for-gcp#151]
Issue came in updating a pipeline or creating a new pipeline.
After digging into stackdriver logs, i found some authorization headers missing errors...

Any suggestions to fix it?

**Comment by duftler** [comment]
I have seen those log entries as well, and don't think it is related to the issue you are describing.

Is the issue persistent? Did this happen once, or is it consistently happening?

You mentioned "updating a pipeline", so I'm thinking you were at some point able to create a new pipeline.

Are you connecting to your Spinnaker via port forwarding or via a domain name? If you are using port forwarding, the most likely culprit is that the port forwarding is no longer in effect. If you still had the UI up in a tab, you wouldn't know this until you tried to push some change or refresh. You can remedy this by re-establishing the port forwarding with the provided command:

![image](https://user-images.githubusercontent.com/8437718/69435213-1c5fd580-0d0d-11ea-9f62-4bc6e8547d1d.png)

**Comment by girisha-g** [comment]
Thanks @duftler for the response.
The issue was persistent but it fixed now.
Had to mention service account access key details in json explicitly in jsonPath for front50
