### ISSUE TITLE
Missing spin-fiat service?

### ISSUE THREAD

**Issue by wilddog64** [GoogleCloudPlatform/spinnaker-for-gcp#155]
When trying to setup spinnaker authorization **fiat** is a required service component, yet I can't see its instance exist

NAME                                READY   STATUS    RESTARTS   AGE
spin-clouddriver-6644cf67bf-vx2sd   1/1     Running   0          21h
spin-deck-6456b4589b-6xlbx          1/1     Running   0          24h
spin-echo-849dc598bf-pg5m8          1/1     Running   0          21h
spin-front50-77c8db5fd6-8262k       1/1     Running   0          23h
spin-gate-855bb68d86-7fgxs          1/1     Running   0          21h
spin-igor-6d4f7f46df-xvmx2          1/1     Running   0          21h
spin-kayenta-56b686f8d6-69m9l       1/1     Running   0          21h
spin-orca-7886f9dd4f-9sngw          1/1     Running   0          21h
spin-rosco-c99589fd9-h6t4z          1/1     Running   0          21h

Although, search fiat from stackdriver, you can find some information regarding to it. So does fiat need to be enabled before running the setup.sh script?

**Comment by duftler** [comment]
We have not worked through configuring fiat with spinnaker-for-gcp yet. I am not really sure what the end result will be with IAP enabled (as it is when securing spinnaker-for-gcp using the provided scripts).

The actual process shouldn't really be any different from doing it with other installations, except that I think we've found a bug with the push_and_apply logic that we need to fix. In the meantime, you can workaround this as follows:

- Use the `hal` cli in cloud shell to enable and configure authorization.
- (This is the workaround) Delete the config file from the halyard daemon pod that is preventing fiat from starting: `kubectl -n halyard exec spin-halyard-0 -- bash -c "rm -rf /home/spinnaker/.hal/default/service-settings/fiat.yml"`
- Push and apply updated config to Spinnaker deployment via the `~/spinnaker-for-gcp/scripts/manage/push_and_apply.sh` script.

The `push_and_apply.sh` script should result in the halyard daemon provisioning a new fiat deployment.

**Comment by duftler** [comment]
I believe the issue with `push_config.sh` is that this change causes the `rm -rf` command to run against a non-existent directory on the pod: https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/commit/b8c26f610f6423093714dcc209794dcb6d5b797e#diff-bb247db2b138af9f7fdc96e977103529L138

**Comment by wilddog64** [comment]
I actually did the hal cli part to configure the authorization to the point I can see the permissions show up. But then it only shows permissions, and missing the role (attached the images). I didn't delete the fiat.yml 
![Screen Shot 2019-12-10 at 12 10 02 PM](https://user-images.githubusercontent.com/746324/70565069-317a9800-1b46-11ea-89c6-84a885027d2e.png)

**Comment by louisjimenez** [comment]
It could be related to the presence of the old `fiat.yml` file where enabled is set to false. Does the issue persist after removing the file and then running the `push_and_apply` script?

**Comment by louisjimenez** [comment]
The PR auto closed this, but feel free to re-open @wilddog64 if that does not address the issue.

**Comment by jaksky** [comment]
Thanks guys for this Issue. Deleting `fiat.yaml` I was able to get the fiat service deployed so I am little bit further than in [issue](https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/issues/207)

Although I am now in either state:
- get 403 access denied - on the URL my_public_iap_url/gate/auth/redirect?to=my_public_iap_url
- get 404 on the url my_public_iap_url/login  which than time-outs - that is when I enable authn [Google OAuth2](https://spinnaker.io/setup/security/authentication/oauth/google/) as described 

I am accessing Spinnaker via IAP configured. Could someone pls clarify if RBAC athorisation can work for spinnaker behin IAP?

Any help would be highly appreciated 
Thanks

**Comment by jaksky** [comment]
@wilddog64 Were you abe to make it work? Did you have IAP in place?

**Comment by wilddog64** [comment]
Well, for now I have no way to test this as I was let go by my previous company and have no GCP access any more
