### ISSUE TITLE
Adding a new pubsub subscription

### ISSUE THREAD

**Issue by damadei-google** [GoogleCloudPlatform/spinnaker-for-gcp#190]
I'm trying to add a new pubsub subscription to Spinnaker for GCP running the following command:

hal config pubsub google subscription add spinnaker-topic-1 --subscription-name spinnaker-topic-1     --project <MY PROJECT> --message-format CUSTOM

After that I ran push_and_apply.sh

However I don't see the subscription available to work as a trigger in Spinnaker console. Am I missing something?

**Comment by duftler** [comment]
I tried creating a new installation from scratch and followed your reproduction steps. The new subscription showed up for me:

![image](https://user-images.githubusercontent.com/8437718/79766222-ab414000-82f5-11ea-8402-e9de624da974.png)


I notice in your command above you have no value for the `--project` argument. Assuming you just removed it for the issue, but worth double-checking.

Could also double-check that the subscription exists and there aren't exceptions in echo's logs.

**Comment by duftler** [comment]
Also need to ensure the new echo pod has come up healthy after running `push_and_apply.sh`.

**Comment by damadei-google** [comment]
Correct, there's an error in echo pod and I'm now unable to connect via hal. I'm deploying a new spinnaker version to test it again. Thanks.

**Comment by damadei-google** [comment]
Worked fine here, seems to be an error in one of my tries. Maybe spinnaker can be better at validating before trying to deploy our changes.
