### ISSUE TITLE
Debian 10 not supported by InstallHalyard.sh and installation from CloudShell fails

### ISSUE THREAD

**Issue by jgracin** [GoogleCloudPlatform/spinnaker-for-gcp#196]
Hi!

CloudShell is on Debian 10 and InstallHalyard.sh reports that the system is not recognized.

BTW, I manually changed the InstallHalyard.sh script to not do anything if on Debian 10 (which effectively makes it use Java 11 instead of Java 8), and everything seems to work so far.

Thanks!

**Comment by plumpy** [comment]
This should be fixed now. Thanks for filing the issue (to both you and @ameer00)!
