### ISSUE TITLE
pull_config.sh is failing to create ~/.hal/config

### ISSUE THREAD

**Issue by bfg-jian** [GoogleCloudPlatform/spinnaker-for-gcp#197]
when running pull_config.sh today it produce following output. It failed to create ~/.hal/config file. It was running fine 2 days ago. could this related to cloudshell OS version?
.  Removing /home/jian_wu/.hal... 
.  Copying halyard/spin-halyard-0:/home/spinnaker/.hal into /home/jian_wu/.hal... 
**cp: cannot stat '.hal/config': No such file or directory**
.  Restoring Spinnaker deployment config files from Kubernetes secret spinnaker-deployment... 
.  Rewriting key path in /home/jian_wu/.spin/config to reflect local user 'jian_wu' on Cloud Shell VM... 
~/cloudshell_open/spinnaker-for-gcp/scripts/install
.  Updating Cloud Shell landing page for secured Spinnaker...

**Comment by bfg-jian** [comment]
Looks like the /home/spinnaker/.hal folder in the spin-halyard-0 pod is empty. This happened after I deleted the existing node pool and created a new one with a different service account.

does deleting the node pool cause hal to lose its config files? does spinnaker-for-gcp back up the configs somewhere permanent?

**Comment by plumpy** [comment]
The `.hal` files are stored in a cloud source repository. You should be able to see them if you go to the URL for your project:
  https://source.cloud.google.com/your-project-id

You likely need to clone those files, replacing the `.hal` directory, and then run `push_config.sh` to make sure Halyard has your up-to-date config.

**Comment by bfg-jian** [comment]
thank you. found the back up files.
