### ISSUE TITLE
Outdated GKE_CLUSTER_VERSION

### ISSUE THREAD

**Issue by kinggreedy** [GoogleCloudPlatform/spinnaker-for-gcp#199]
According to https://cloud.google.com/kubernetes-engine/docs/release-notes#august_06_2020_r26 , ver 1.14 will no longer after 6th Aug 2020, we have to use 1.15.12 instead

So modifying https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/blob/master/scripts/install/setup_properties.sh#L155 to `export GKE_CLUSTER_VERSION=1.15.12` seems to fix the problem

**Comment by duftler** [comment]
Thanks for raising the issue. If you'd like to submit a PR I can review it.

**Comment by kinggreedy** [comment]
@duftler I made the PR for the issue. I'm not sure if my solution is the best since I'm not familiar with GCP. However, changing to version 1.15.12 is the way my Qwiklabs could be proceed.

**Comment by plumpy** [comment]
Thanks for the fix!
