### ISSUE TITLE
grant_iap_access.sh failing with 400 INVALID_ARGUMENT

### ISSUE THREAD

**Issue by jaksky** [GoogleCloudPlatform/spinnaker-for-gcp#202]
~/cloudshell_open/spinnaker-for-gcp/scripts/manage/grant_iap_access.sh
Please enter the member you wish to grant the 'IAP-secured Web App User' role.
Note that you must include the correct prefix depending on the type of member.
These are the supported types:
  user:some-user@somedomain.net, serviceAccount:some-service-account@some-project.iam.gserviceaccount.com, group:some-group@somedomain.net, domain:somedomain.net
Member to add: spinnaker-acc-1599740941@xxx.iam.gserviceaccount.com

~/cloudshell_open/spinnaker-for-gcp/scripts/install ~/.spin
.  Querying for backend service id... 
.  Querying for existing IAM policy... 
.  Granting member spinnaker-acc-1599740941@xxx.iam.gserviceaccount.com the 'IAP-secured Web App User' role... 
{
  "error": {
    "code": 400,
    "message": "The member spinnaker-acc-1599740941@xxx.iam.gserviceaccount.com is of an unknown type. Please set a valid type prefix for the member.",
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by duftler** [comment]
I think the argument has to be formatted as described in the prompt:
`serviceAccount:spinnaker-acc-1599740941@xxx.iam.gserviceaccount.com`

**Comment by duftler** [comment]
But are you sure that is the member you want to grant access to? What are you trying to change? Are you trying to enable access for yourself (that is, for your user id), or something else?

**Comment by duftler** [comment]
If you've used the included scripts to enable IAP and secure Spinnaker, your use should already be able to access it via `spin`.

**Comment by jaksky** [comment]
This is first time for me with Spinnaker at all and I was following Tutorials to get it installed. I configured it based on tutorials and `spin` wasn't working for me. I spend some time until I discovered what account is configured for spin and find out that was missing in IAP so was trying to add it to make it work I used the script above. And yes, sorry that was probably wrong compy/paste issue as I was trying various alternatives but I was trying correct format as well `serviceAccount:service-account@...` and was getting this error as well. I took the account that was configured for spin in .spin/config

**Comment by duftler** [comment]
I tried copying/pasting my way through the instructions from scratch just now, and I was able to provision Spinnaker and then to enable access to it via IAP. I didn't take any steps outside of what is explicitly advised in the Spinnaker for GCP guidance. I did this in a brand new GCP project.

Note that it does take some time for the IAP and related configuration to complete, and spin commands result in an error message if one hasn't waited long enough:
```
$ spin application list
Could not reach Gate, please ensure it is running. Failing.
Get https://spinnaker-1.endpoints.rosco-oss-240.cloud.goog/gate/version: remote error: tls: handshake failure
```

After waiting a while though, I get:
```
$ spin application list
[
 {
  "cloudProviders": "kubernetes",
  "createTs": "1600355181302",
  "email": "duftler@google.com",
  "instancePort": 80,
  "lastModifiedBy": "anonymous",
  "name": "testapp1",
  "trafficGuards": [],
  "updateTs": "1600355181407",
  "user": "[anonymous]"
 },
 {
  "accounts": "spinnaker-install-account",
  "name": "kubernetes"
 }
]
```

Note that all of this was done solely inside of the Cloud Shell terminal.

**Comment by jaksky** [comment]
Ok, I might mess something. I will try to reinstall later on. Thx for the replies!
