### ISSUE TITLE
Unable to update Spinnaker version

### ISSUE THREAD

**Issue by jianglai** [GoogleCloudPlatform/spinnaker-for-gcp#223]
We have a spinnaker instance (1.21.1) managed by the Spinnaker for GCP scripts. While trying to upgrade to 1.25.3 I am getting the following error:

```
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Validation in Global:
! ERROR No persistent storage type was configured.
- Failed to deploy Spinnaker.
```

I'm not sure what has changed as the last time we upgrade it was successful. The persistent storage is probably referring to GCS but I don't know where to configure it.

Any insights would be helpful.

Thanks.

**Comment by plumpy** [comment]
Ah, I see what happened. So your Cloud Shell got reprovisioned or something and it deleted all your data.

All your config is stored in a [Cloud Source Respository](https://source.cloud.google.com/). You can get it back by running the `spinnaker-for-gcp/scripts/manage/pull_config.sh` script.

**Comment by jianglai** [comment]
We always use the `update_console.sh` script to do the upgrade, doesn't that include a step to run `pull_config.sh`?

Also, from what I can find the `pull_config.sh` script pull the config [from the halyard daemon container](https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/blob/be4bfd26f26cba3ee7618e5b80756b826626bc8a/scripts/manage/pull_config.sh#L38). If it is indeed saved in a CSR, is it possible to download it directly?

**Comment by plumpy** [comment]
Yeah, if you go to `https://source.cloud.google.com/YOUR_PROJECT_ID` you should see the repo there with a `.hal/config` file within. You could even just copy/paste it.

**Comment by plumpy** [comment]
Actually, I suppose you'll need the whole `.hal` directory, so you'll probably want to [clone it](https://cloud.google.com/source-repositories/docs/cloning-repositories) and then copy the `.hal` directory into your cloud shell homedir.

**Comment by jianglai** [comment]
Ah, you are right. It is there. Now it confuses me a bit, why does the `pull_config.sh` script pull from the container in this case then? Which one is considered the source of truth?

**Comment by jianglai** [comment]
And to add on that, I do see that the repo has been wiped by the script when I run it on 3/22, the last time I run before that was on 9/10, and it only updated the config instead of wiping it.

**Comment by jianglai** [comment]
Lastly, I was able to copy the config from 9/10 and update the spinnaker instance, thanks!

**Comment by plumpy** [comment]
I'm going to close this but let me know if you're still having issues...
