### ISSUE TITLE
Multi-instance setup

### ISSUE THREAD

**Issue by jianglai** [GoogleCloudPlatform/spinnaker-for-gcp#50]
What is the proper way to manage multiple Spinnaker instances (one for testing and one for production)? As far as I can tell I have only one Cloud Shell home directory, so I created two separate folders, each containing its own `spinnaker-for-gcp` folder, to keep the `properties` file seperate. And I think I need to run `scripts/manage/pull_config.sh` every time I want to switch instances (which overwrites the `~/.hal` folder with the configs from the instance to manage, as I understand it).

Is this the right way to do this? It is a bit annoying in that all the tutorials assume that `spinnaker-for-gcp` is directly under home, so all the commands you can copy from the tutorials start with `~/spinnaker-for-gcp/`

**Comment by duftler** [comment]
Definitely don't create multiple folders for multiple `spinnaker-for-gcp` installations.

The design is such that you will only need one `spinnaker-for-gcp` repo checked out, and it can be destroyed and re-cloned at any time.

Any time you want to manage a Spinnaker installation, you take the steps outlined in the [readme](https://github.com/GoogleCloudPlatform/spinnaker-for-gcp) under [Ongoing management of Spinnaker](https://github.com/GoogleCloudPlatform/spinnaker-for-gcp#ongoing-management-of-spinnaker).

One step to pay special attention to is this one: "make sure you're connected to the GKE cluster containing the Spinnaker instance you want to manage."

The cluster you are connected to is always the source of truth for your Spinnaker configuration. Any time you want to manage the installation, you first pull the config into your cloud shell environment. It will always override whatever config you happen to have locally in cloud shell prior to the pull command.

You make your management changes and push & apply the config. The push & apply command also implicitly creates a full config backup in a gcs bucket.

You can have multiple GKE clusters in a GCP project, and each can contain at most 1 Spinnaker installation. The installation themselves can be used to manage as many GKE clusters as you like, but you can't install more than one Spinnaker in a given GKE cluster.

So long as you always ensure you are connected to the correct GKE cluster prior to performing managements tasks, you can safely manage multiple Spinnaker instances.

**Comment by jianglai** [comment]
What about the `properties` file? Does it gets updated when you pull the configs from your Spinnaker instance? I'm asking because it is certainly used *after* installation. For instance you'd bump the spinnaker version number there. So if I want to keep different Spinnaker instances on different versions, the `properties` file needs to be in sync with the instance being managed.

**Comment by duftler** [comment]
Yes, it gets updated along with all the other relevant config files.

You can get a better idea of the bits that are updated from this list in the script: https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/blob/master/scripts/manage/pull_config.sh#L70-L78

You should feel free to completely remove the `spinnaker-for-gcp` directory and any other config files at any point when you are not actively performing some command (assuming you have pushed/applied any pending changes to an instance).

**Comment by jianglai** [comment]
OK that's really helpful! I'll close this issue for now. Will reopen if I run into issues with managing multiple instances.

**Comment by duftler** [comment]
Great. We'll also add additional details to the docs about this. Thanks for raising the issue.

fyi @dorbin

**Comment by jianglai** [comment]
OK I think there is indeed a bug with how multiple instances of Spinnakers are managed. Namely when [`check_cluster_config.sh`](https://github.com/GoogleCloudPlatform/spinnaker-for-gcp/blob/master/scripts/manage/check_cluster_config.sh) checks if the current kubernetes context contains a Spinnaker instance, it uses the default context. It that cluster happens to contain a Spinnaker instance, the check will pass and configs will be pulled from there. However when you have multiple instances to manage, the default context may very well point to a cluster in a project other than the one you are meant to manage. The `PROJECT_ID` variable in `check_cluster_config.sh` has no bearing on if the current cluster happens to contain a Spinnaker instance. So it is very likely that a user will be administering a wrong Spinnaker instance

**Comment by jianglai** [comment]
@duftler FYI

**Comment by duftler** [comment]
@jianglai Thanks for raising this issue and for the detailed explanation of why the original approach wasn't quite right.
