### ISSUE TITLE
Evaluate using Kapitan? https://github.com/deepmind/kapitan

### ISSUE THREAD

**Issue by ademariag** [GoogleCloudPlatform/spinnaker-for-gcp#67]
Hello,

I am using this repo to setup my test Spinnaker and it works great.

However I was going to suggest using Kapitan to generate the scripts and manage the deployment. You would be able to simplify lots of your logic and you would be able to support multiple deployment out of the box.

contact us on the #kapitan channel on Kubernetes slack if you need help.

**Comment by demobox** [comment]
Thanks for the suggestion! Spinnaker currently already supports the notion of Kubernetes config transformation as part of the pipeline (we're not currently demoing that in the sample application, but definitely could). It currently [works for Helm](https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/) as that's what was most frequently requested, but it certainly would be possible to extend that to Kapitan if there's interest.

Contributions to spinnaker/spinnaker very welcome, of course!
