### ISSUE TITLE
Creating with a service account via cloud shell?

### ISSUE THREAD

**Issue by adamdavis40208** [GoogleCloudPlatform/spinnaker-for-gcp#71]
New to GCP so apologies if this is off-topic. 

We would like to try this, but we currently install everything (and manage everything) via least-privilege service accounts.

Is it possible to run cloud shell as a service account, or are there any instructions on running this through gcloud without cloud shell?

Thanks!

**Comment by demobox** [comment]
Hi Adam

Thanks for reaching out! A couple of points in response to your question:

* Once the `properties` file for your Spinnaker for Google Cloud Platform instance is generated, it should be possible to run the installation script using any set of gcloud credentials, including a service account. There are a couple of commands in the script that will likely need to be modified (such as the steps that update the UI of the management environment), but these should not be critical to the operation. This is not a scenario we have tested yet, though

* We're in the process of better documenting the permissions required to install and manage Spinnaker for GCP, and will likely look into minimizing the set of required permissions if possible. /cc @dorbin on this

* A roadmap item we are also looking into is a more general "infra-as-code" mechanism for installing and managing Spinnaker for GCP

Out of curiosity, would you be looking to install and manage this as part of a workflow in which you also administer other settings? If so, are you using an infra-as-code tool (e.g. Terraform or Cloud Deployment Manager) to do this?

**Comment by adamdavis40208** [comment]
We currently use terraform for everything GCP, and would definitely love a terraform approach to this setup.

I'll dig into creating the properties file and see if I can get this installed with a service account. Thanks for the reply!

**Comment by demobox** [comment]
> I'll dig into creating the properties file and see if I can get this installed with a service account.

Please follow up with comments if you run into any issues!

**Comment by adamdavis40208** [comment]
No issues, but just wanted to follow up (now that I'm more comfortable with gcp).

We created a properties file, that we're now storing in git. 

We're storing the properties file and the service account json in a gcs bucket.

My user has permissions to this bucket. 

After cloning the repo by clicking on the link in the market, just download the contents of your bucket. 

These two commands set your local gcloud to the service account json you downloaded (here named auth.json)
```
export GOOGLE_APPLICATION_CREDENTIALS=./auth.json
gcloud auth activate-service-account --key-file=~/auth.json
```

Now any commands you run will be using the service account. The list of permissions needed for least privilege are still a bit unknown, but we're getting by with:

```
Environment and Storage Object Administrator
Editor
Role Administrator
Service Account Admin
Storage Admin
VPC Controls Manager
Security Reviewer 
```

**Comment by demobox** [comment]
Thanks for the update, @adamdavis40208! FYI @duftler on this
