### ISSUE TITLE
Question:  IAP Access

### ISSUE THREAD

**Issue by camechis** [GoogleCloudPlatform/spinnaker-for-gcp#73]
I have installed spinnaker-for-gcp and setup it up to be public facing with IAP.  The question I have is currently I am the only user listed under IAP users.  The Oauth portion of spinnaker allows anyone in my particular google domain.  I noticed any user in my domain could log into spinnaker which makes since thats how the Oauth part is configured but I thought IAP would block access since I Am the only user listed.  Is this correct ? I may be misunderstanding how the IAP and the spinnaker OAuth work together.

**Comment by duftler** [comment]
Can you provide more details about how you configured Spinnaker? Not sure exactly what you mean when you say the oath portion of Spinnaker allows anyone in your domain.

If you follow through the Spinnaker for GCP installations steps without deviation, the end result is IAP configured to allow only the admin doing the installation to reach Spinnaker through IAP. To allow additional users to access Spinnaker, you can use the script provided with the management console:

https://screenshot.googleplex.com/0gNi5MrPHVm.png
![image](https://user-images.githubusercontent.com/8437718/62061556-68828980-b1f5-11e9-9f5e-be849621d1ff.png)

When you run that script, you can choose what type of member to add:

user:some-user@somedomain.net, serviceAccount:some-service-account@some-project.iam.gserviceaccount.com, group:some-group@somedomain.net, domain:somedomain.net

I believe only listed IAP members should be able to reach Spinnaker through IAP.

**Comment by camechis** [comment]
I just followed the instructions through the cloud console shell.  When I talk about the spinnaker oauth I am talking about the configuration that sets the redirect URL and such.

I thought I would be the only one able to access it but my co-worker was able to login into it as well with his work gmail.

**Comment by camechis** [comment]
I figured out the issue,  my co-worker had his host file incorrect and he was actually hitting our previous spinnaker instance without IAP.  Once that was corrected everything worked just fine
