### ISSUE TITLE
Adding docker registry

### ISSUE THREAD

**Issue by matthewduval** [GoogleCloudPlatform/spinnaker-for-gcp#74]
I'm having issues attempting to add a private GCR docker registry to spinnaker.  I'm attempting to follow the instructions provided by spinnaker here: [https://www.spinnaker.io/setup/install/providers/docker-registry/#google-container-registry].  I've placed the json key file in my ~/.hal/default/credentials directory, and I'm able to successfully add the registry to the config locally, however when I run the push_and_apply.sh script, I receive the following error:  

Problems in default.provider.dockerRegistry.prod-registry:
! ERROR Cannot find provided path:
  /home/user1/.hal/default/credentials/gcr-account.json (No such file or
  directory).: /home/user1/.hal/default/credentials/gcr-account.json (No such
  file or directory).

I am adding the docker registry account to the local hal config with the following command:

~/hal/hal config provider docker-registry account add prod-registry \
 --address gcr.io \
 --username _json_key \
 --password-file ~/.hal/default/credentials/gcr-account.json

This file definitely exists in this path, and I was able to successfully add a gke account using the provided script.  Any ideas as to why I receive this error?

**Comment by duftler** [comment]
Pretty sure I know what this is. Working on reproducing now.

**Comment by duftler** [comment]
Have reproduced.

I believe the issue is that I neglected to include the name of the attribute that references the GCR json key file in the list used by the push/pull rewriting logic. Looking now...

**Comment by duftler** [comment]
Yup, that was the problem. Fix on its way...

**Comment by duftler** [comment]
You can pick up the fix by upgrading your management environment via the included command:

![image](https://user-images.githubusercontent.com/8437718/62150951-3c3a3c00-b2cd-11e9-89d7-60168c231063.png)

**Comment by duftler** [comment]
Btw, the reason for the rewriting logic is that the username in the halyard pod is `spinnaker`, and this will not match your username in cloud shell. So we rewrite paths that include the username on both push and pull.

**Comment by matthewduval** [comment]
Ah, okay that makes sense.  I can confirm it's working now for me.  Thanks very much for the quick response.
