### ISSUE TITLE
spin-fiat pod not deployed

### ISSUE THREAD

**Issue by kumarpramod** [GoogleCloudPlatform/spinnaker-for-gcp#87]
It seems the installation process does not deploy fiat pod. It did not deploy fiat pod even after enabling the feature fiat in ~/.hal.config file.

**Comment by Tangeek59** [comment]
Hello,

I had the same issue when trying to deploy it.
After editing the file `~/.hal/default/service-settings/fiat.yml` to :
```
enabled: true
skipLifeCycleManagement: false
```

It worked for me

**Comment by kumarpramod** [comment]
@Tangeek59 Thank you so much. It works for me after applying your suggestions.

**Comment by kumarpramod** [comment]
@Tangeek59  solution works.
